name: API Testing

on:
  push:
    branches: [ "master", "main"]
  pull_request:
    branches: [ "master", "main"]
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies in API tests folder
      run: cd ./api-tests && npm ci

    - name: Run API tests for ReportPortal API
      run: cd ./api-tests && npm run test
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        

    

